apiVersion: v1
kind: Secret
metadata:
  name: chat-db-secret
  namespace: chat-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  # Backend ke liye connection string
  MONGO_URI: "mongodb://root:admin@mongodb-svc:27017/chatApp?authSource=admin"
  JWT_SECRET: "your_jwt_secret_key"
